apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: secops
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - >-
              until pg_isready -h postgres -p 5432
              -U "$POSTGRES_USER" -d "$POSTGRES_DB";
              do echo "Esperando a PostgreSQL..."; sleep 3; done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: POSTGRES_DB
      containers:
        - name: backend
          image: retlaw2002/secops-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: secops-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: POSTGRES_DB
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secops-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 8
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secops
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: http
